### ISSUE TITLE
Switch from Local to Bank boxes on O3DS/2DS

### ISSUE THREAD

**Issue by fsegouin** [gocario/PHBank#12]
Since O3DS and 2DS don't have LZ/RZ buttons, maybe mapping this function to a combo of other buttons would be nice?

**Comment by gocario** [comment]
The LZ/RZ mapping is only a bonus for n3ds.
The o3ds/2ds can move into the bank by accessing the border of the box using the Left/Right of the DPad, or by touching the bank rectangle with the stylus (for drag&drop). It's the same for going back to the PC.
