### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by giveup** [gocario/PHBank#14]
log:
linking PHBank.elf
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/5.3.0/../../../../arm-none-eabi/bin/ld: cannot find -lfreetype
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/5.3.0/../../../../arm-none-eabi/bin/ld: cannot find -lpng
/opt/devkitpro/devkitARM/lib/gcc/arm-none-eabi/5.3.0/../../../../arm-none-eabi/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
make[1]: **\* [/Documents/PHBank/PHBank.elf] Error 1
What dependence or lib is missing?

**Comment by gocario** [comment]
You are needing the portlibs, I'm using those from [xerpi's fork](https://github.com/xerpi/3ds_portlibs).

**Comment by giveup** [comment]
@gocario Hi,after install portlibs,still unable to compile.

linking PHBank.elf
am.o: In function `AM_GetPokemonTitleEntryList':
/Documents/PHBank/source/am.c:105: undefined reference to`AM_GetTitleIdList'
/Documents/PHBank/source/am.c:108: undefined reference to `AM_GetTitleIdList'
collect2: error: ld returned 1 exit status
make[1]: **\* [/Documents/PHBank/PHBank.elf] Error 1

Thanks and Regards.

**Comment by gocario** [comment]
I think you have an outdated ctrulib.
Update it and try again.

**Comment by giveup** [comment]
Nope,I already install latest libctru. Does it need specify ctrulib fork?

**Comment by gocario** [comment]
My bad, I didn't know that the clean up of the am service has been merged.
I pushed a commit to fix that.
Sorry

**Comment by giveup** [comment]
@gocario Well,The build is sucess but failed to launch.
The top screen display error:
Problem happened 0x20
*Graphics
PHBank version 020001b0
Can't start the viewer
Press any key to exit
Test on cia build.

**Comment by gocario** [comment]
Do you have the /pk/ folder at the root of your sd card with the romfs filled as in the release zip?
You can try to update it with [PKBrew](https://github.com/gocario/PKBrew).

**Comment by giveup** [comment]
@gocario Finally,Works greak! Just put latest /pk/ folder to SDMC.
Will it add multilanguage support?
