### ISSUE TITLE
Crash related to cursor

### ISSUE THREAD

**Issue by Wheth** [gocario/PHBank#16]
When you grab a Pokémon and try to change the current box by moving the cursor over the box name (where you could move left and right to change box) the application crashes and the console forces a reboot.

Can easily be reproduced by grabbing a Pokémon from the save file and pressing "up" until it crashes.

Moving the cursor (with the grabbed Pokémon) around for a while, then trying to change boxes does not trigger a crash. It only happens when trying to change the box right after grabbing the Pokémon.

L and R are unaffected.

**Comment by gocario** [comment]
Shall be fixed with a01c6b77880b402f0ef9043038bbb431b1cc8e2f

**Comment by Wheth** [comment]
Confirmed, works great ;) Thanks!
