### ISSUE TITLE
Wurmple's evolution: anyone cares?

### ISSUE THREAD

**Issue by Wheth** [gocario/PHBank#17]
So, I wanted to check what Wurmple would evolve to, the easy and fast way: asking PHBank to tell me. And now, tell me it does.

Is it relevant enough for a pull request, or nobody but me ever cared/cares? :P

**Comment by suloku** [comment]
http://bulbapedia.bulbagarden.net/wiki/Personality_value#Wurmple.27s_evolution

I guess showing a silcoon/cascoon "icon sprite" on upper screen somwhere would work?

**Comment by Wheth** [comment]
On generation 6 it's the higher 16 bits of the encryption constant that determines evolution (got a legion of Wurmples/evolutions thanks to that change. Thought it was the PID like the other gens :P).

The sprites are almost identical, and it would be hard to tell them apart, I think. But I'm not sure if a "Evolves into Silcoon/Cascoon" text is appropriate. Seems a bit overkill.

Maybe just writing "Silcoon" or "Cascoon" somewhere?

**Comment by suloku** [comment]
the sprites are hard... then why not beautifly/dustox instead? I can't compile phbank due to not being able to compile freetype portlib, or I'd make a pull request

**Comment by Wheth** [comment]
That's a good idea :P think this looks good enough?

http://imgur.com/RQfUwo4

**Comment by gocario** [comment]
That is clever. :+1:
I guess we can display it w/e it's an egg or a real wurmple.
I am awaiting your PR then.

**Comment by Wheth** [comment]
Done!

**Comment by gocario** [comment]
I cleaned up your PR a bit: a351f2bc9505938da1fc2368d1f6b11f52e76309
The icon will be shiny depending on the wurmple's shinyness.
