### ISSUE TITLE
Cannot link, since undefined reference to `AM_GetTitleList'

### ISSUE THREAD

**Issue by bulldog98** [gocario/PHBank#19]
I tried to build the repro today, but it failed linking because in line 105 and 108 of am.c it uses AM_GetTitleList, but this is not found.

**Comment by gocario** [comment]
Update your libctru.
It has been renamed some commits before.
https://github.com/smealum/ctrulib/commit/932630764f04ee2b6f510fe69bb8db1249f1f541#diff-e929320527f19526d7fd64e2c95a107aL40

**Comment by bulldog98** [comment]
Ok I'll try that.

Edit: Tried that fixed this problem
