### ISSUE TITLE
Target PHBank.3dsx fails

### ISSUE THREAD

**Issue by bulldog98** [gocario/PHBank#20]
If I try to build the cia file I get:

```
stat() failed

/opt/devkitpro/devkitARM/3ds_rules:34: die Regel für Ziel „~/Develop/Homebrew/PHBank/PHBank.3dsx“ scheiterte
```

**Comment by gocario** [comment]
It failed at: `@3dsxtool $< $@ $(_3DSXFLAGS)`
I guess you haven't 3dsxtool in your path.
Try to update DevkitPro, or download 3dsxtool from somewhere else.

**Comment by bulldog98** [comment]
Nope it's in path I guess it's about not having the romfs directory, but even with the romfs directory from your PKBrew repo it would not work

**Comment by gocario** [comment]
Comment that line: https://github.com/gocario/PHBank/blob/master/Makefile#L41
By adding a # at the start.
Then try to compile again.

**Comment by bulldog98** [comment]
Yes that fixes the problem thanks
