### ISSUE TITLE
About box unlocking

### ISSUE THREAD

**Issue by Wheth** [gocario/PHBank#21]
So, I was comparing changes in savefiles made between PHBank, PKHex and an elapsed PokéBank account, when I saw that PHBank seems to unlock every locked box in the savegame (or atleast, changing this one byte: https://github.com/gocario/PHBank/blob/master/source/save_manager.cpp#L609).

Just curious, is there a reason for it? PokéBank seems to ignore it.

**Comment by suloku** [comment]
Official bank unlocks all boxes until box 30. That's what phbank does.
EDIT: of course, if you don't save in official bank, boxes aren't unlocked.

Box 31 can only be unlocked in-game, even if using official bank.
