### ISSUE TITLE
Therian Forms of Tornadus, Thundurus, and Landorus not displaying correctly

### ISSUE THREAD

**Issue by d4mation** [gocario/PHBank#23]
Using b402734 of PHBank and gocario/PKBrew@e20068a.

Landorus shows as a green square, Tornadus and Thundurus show as Female Frillish and Female Jellicent respectively within the Box View.

Full-size Sprite on the top screen doesn't show them as Therian form either.

In this case all three should be in Dream Balls (Obtained via [Pokemon Dream Radar](http://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Dream_Radar)), but they are showing as caught in a Park Ball.

![image](https://cloud.githubusercontent.com/assets/7770631/15374489/949dae5c-1d18-11e6-83a2-0417ff711aa4.png)

![image](https://cloud.githubusercontent.com/assets/7770631/15374493/99e9ab04-1d18-11e6-81b1-1ee00dfbdd6f.png)

![image](https://cloud.githubusercontent.com/assets/7770631/15374474/87f4d144-1d18-11e6-8d6f-6764c0cf6b6a.png)

**Comment by gocario** [comment]
Can you try with these modified files from that commit:
https://github.com/gocario/PKBrew/commit/7d69e40a43a23c994d8f6f22cb87583e30f9650c
PS: I don't render the form on the top screen icon for the moment, because I don't have the arts.

**Comment by d4mation** [comment]
That does fix the problem with their icons not loading properly in the box view for those forms, but now Female Frillish/Jellicent won't load properly since they've been removed from the spritesheet.

Is there a particular reason that all the Megas are in the spritesheet? Outside of cheating, a Pokemon shouldn't be able to go into the PC as a permanent Mega. Those may be a better candidate for removal if it is a space issue.

Ah, and you're right about the top screen. I didn't notice that no forms were included in that folder within `romfs` at all.

**Comment by gocario** [comment]
Can you try again with these two commits:
https://github.com/gocario/PHBank/commit/e368db8762f59af07623404899246c0634e9734e
https://github.com/gocario/PKBrew/commit/7bcfe640b5c1052c1ca7c08fb8ddfa0a1b5a68ad

There is too much Pokémon forms (excluding non PCable) to be contained in the normal spritesheet, that is why I had to use another one.

**Comment by d4mation** [comment]
Sorry, I've been away from my computer that has CTRULIB and such set up for a couple days.

Using the latest commits of both PHBank and PKBrew:

3DSX: Crashes after game selection.

```
Problem happened: 0x84
* Save
* Filesystem
PHBank version: 020001b0
```

CIA: Still shows the male forms for Pyroar, Unfeazant, and Frillish/Jellicent when viewing a Female Pokemon.

Otherwise, the Therian Form issue has been fixed.

**Comment by gocario** [comment]
I did a new commit, which shall fix the females forms for these 4 species: https://github.com/gocario/PHBank/commit/e23208aae7c6bdf3fa9ca38a0dd2b91adfa08255
Keep in mind that for CIA build you need to have a __cia defined, and nothing special for the 3DSX
Check that: https://github.com/gocario/PHBank/blob/master/Makefile#L60 -D__cia will define __cia in the compilation, remove it for the 3dsx build.

**Comment by d4mation** [comment]
The CIA build is showing the proper forms for me now. The 3DSX is still crashing with the same error as before and I really have no idea why, but I personally use the CIA anyway. It must just be something funky with my setup since theoretically they should be running the precisely the same code, right?

Regardless, Issue closed! Thanks for looking into this, @gocario!
