### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by alexwilson** [gocario/PHBank#25]
Hey,

I'm not entirely sure that PokemonGB, licensed as "Freeware", is compatible with the GPL v3 license that you're distributing this project under.  Would it be possible to determine what this actually means?

**Comment by SciresM** [comment]
It's compatible. 

Per [the GPL's guide](http://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses),

"Informal License" is compatible with GPL, and the "Freeware" license used for PokemonGB states "Free to use for both Personal and Commercial".
