### ISSUE TITLE
PHBank Not Launching

### ISSUE THREAD

**Issue by Anonymous42456** [gocario/PHBank#30]
PHBank won't launch. I keep getting this error:

"Problem happened: 0x28
PHBank version: 020001b0
Can't start the viewer.
Press any key to exit."

**Comment by colmlg** [comment]
You didnt copy the extra folder to the SD card.

**Comment by brian-ding** [comment]
I have the same error here, and I am sure that I copied everything into SD card

**Comment by Anonymous42456** [comment]
Even the pk folder?

**Comment by brian-ding** [comment]
alright, solved, 
the thing is I extracted three folders in a parent folder and copy the parent folder to the root of SD card

**Comment by gocario** [comment]
Yeah, PHBank needs its resource files located in the /pk/ folder.
Latest version describe quickly which "module" failed.
