### ISSUE TITLE
Bank file causes chrash

### ISSUE THREAD

**Issue by mmaestredev** [gocario/PHBank#35]
Story: did the Plailect guide again, updated to latest console firmware, installed Phbank. 

Phbank crashes and forces to restart the console. I tested with another bank file (which is almost empty)  and it works fine, but the one with most of my pokes won't, please help me:'(

**Comment by gocario** [comment]
Have you mess up with some PHBank different versions?
Do you have bank backups?

**Comment by mmaestredev** [comment]
Oh hello there.. Actually, the problems was caused by the ftp homebrew.. It corrupts save files for some reason. Lucky me i found a backup.. I thought I didn't have one when created the issue.
Sorry, and keep up the good work. Hope you manage to get this working for Sun & Moon :D
