### ISSUE TITLE
Yellow screen on phbank with 11.1

### ISSUE THREAD

**Issue by fennectech** [gocario/PHBank#36]
I updated to 11.1 today and now phbank is failing to start with a yellow screen

**Comment by gocario** [comment]
That is related to the PASLR, not to PHBank afaik.
For the future, please provide more informations on your problem.

**Comment by fennectech** [comment]
The developers of JK save tool have found a workarround using pokemon bank        i havent looked into it   but i thought i would let you know

**Comment by fennectech** [comment]
https://github.com/J-D-K/JKSM

**Comment by fennectech** [comment]
A simple workarround would to give the ability to work on save backups    and let the user backup and restore them
