### ISSUE TITLE
Support for Pokemon Sun , Moon ,Ultra Sun ,Ultra Moon

### ISSUE THREAD

**Issue by HugeKC01** [gocario/PHBank#39]
I hope Pokemon homebrew bank will support pokemon SMUSUM

**Comment by DD2XAlpha** [comment]
Me too

**Comment by gocario** [comment]
You should better use PKSM now.

**Comment by AlMcKinlay** [comment]
@gocario Just an FYI, if you don't plan on updating and are fed up of getting notifications from people, you can archive the repo in github and people can't add new issues.
